Improved loading script configuration

diff --git a/sandbox/add_sandbox_account b/sandbox/add_sandbox_account
--- a/sandbox/add_sandbox_account
+++ b/sandbox/add_sandbox_account
@@ -8,13 +8,6 @@ set -o pipefail
 
 DEFAULT_SANDBOX_SCRIPT_CONF="${HOME}/sandbox/scripts/sandbox_script.conf.default"
 
-# Inlcude script configuration
-if [[ -n "${SANDBOX_SCRIPT_CONF}" ]]; then
-  source "${SANDBOX_SCRIPT_CONF}"
-else
-  source "${DEFAULT_SANDBOX_SCRIPT_CONF}"
-fi
-
 # Output utilities
 err() {
   echo -e "$@" >&2
@@ -26,6 +19,19 @@ failed() {
   printf "\033[0m\n" >&1  # reset color for stdout
 }
 
+# Inlcude script configuration
+readonly SCRIPT_CONF="${SANDBOX_SCRIPT_CONF:-${DEFAULT_SANDBOX_SCRIPT_CONF}}"
+if [[ -n "${SCRIPT_CONF}" ]]; then
+  source "${SCRIPT_CONF}"
+  if [[ "$?" -ne 0 ]]; then
+    err "Failed to load script configuration: ${SCRIPT_CONF}"
+    exit 5
+  fi
+else
+  err "Script configuration is not specified"
+  exit 4
+fi
+
 # Validate command parameters
 if [[ "$#" -lt 1 ]]; then
   err "Usage: $(basename "$0") <sandbox_id>"
@@ -35,14 +41,27 @@ fi
 # Set variables
 readonly ID="$1"
 
-if [[ -n "${SANDBOX_USERNAME_INIT}" ]]; then
+if [[ -n "${SANDBOX_USERNAME_INIT+x}" ]]; then
   readonly GROUP="${SANDBOX_USERNAME_INIT}"
 else
   readonly GROUP="${DEFAULT_USERNAME_INIT}"
 fi
 
-readonly USERNAME="${GROUP}-${ID}"
-readonly USER_HOME="/home/$USERNAME"
+if [[ -n "${GROUP}" ]]; then
+  readonly USERNAME="${GROUP}-${ID}"
+else
+  readonly USERNAME="${ID}"
+fi
+
+if [[ -n "${SANDBOX_USER_HOME_ROOT}" ]]; then
+  readonly USER_HOME_ROOT="${SANDBOX_USER_HOME_ROOT}"
+elif [[ -n "${DEFAULT_USER_HOME_ROOT}" ]]; then
+  readonly USER_HOME_ROOT="${DEFAULT_USER_HOME_ROOT}"
+else
+  readonly USER_HOME_ROOT="/home"
+fi
+
+readonly USER_HOME="${USER_HOME_ROOT}/$USERNAME"
 
 if [[ -n "${SANDBOX_PASSWORD_INIT}" ]]; then
   readonly PASSWORD="${SANDBOX_PASSWORD_INIT}${ID}"
@@ -89,7 +108,11 @@ if [[ -n "$(getent group "${USERNAME}")" ]]; then
 fi
 
 # Create account
-sudo useradd -G "${GROUP}" "${USERNAME}" -m -s /bin/bash
+if [[ -n "${GROUP}" ]]; then
+  sudo useradd "${USERNAME}" -G "${GROUP}" -m -d "${USER_HOME}" -s /bin/bash
+else
+  sudo useradd "${USERNAME}" -m -d "${USER_HOME}" -s /bin/bash
+fi
 
 RET="$?"
 if [[ "${RET}" -ne 0 ]]; then
diff --git a/sandbox/chg_sandbox_account_password b/sandbox/chg_sandbox_account_password
--- a/sandbox/chg_sandbox_account_password
+++ b/sandbox/chg_sandbox_account_password
@@ -8,13 +8,6 @@ set -o pipefail
 
 DEFAULT_SANDBOX_SCRIPT_CONF="${HOME}/sandbox/scripts/sandbox_script.conf.default"
 
-# Inlcude script configuration
-if [[ "${SANDBOX_SCRIPT_CONF}" ]]; then
-  source "${SANDBOX_SCRIPT_CONF}"
-else
-  source "${DEFAULT_SANDBOX_SCRIPT_CONF}"
-fi
-
 # Output utilities
 err() {
   echo -e "$@" >&2
@@ -26,6 +19,19 @@ failed() {
   printf "\033[0m\n" >&1  # reset color for stdout
 }
 
+# Inlcude script configuration
+readonly SCRIPT_CONF="${SANDBOX_SCRIPT_CONF:-${DEFAULT_SANDBOX_SCRIPT_CONF}}"
+if [[ -n "${SCRIPT_CONF}" ]]; then
+  source "${SCRIPT_CONF}"
+  if [[ "$?" -ne 0 ]]; then
+    err "Failed to load script configuration: ${SCRIPT_CONF}"
+    exit 5
+  fi
+else
+  err "Script configuration is not specified"
+  exit 4
+fi
+
 # Validate command parameters
 if [[ "$#" -lt 2 ]]; then
   err "Usage: $(basename "$0") <sandbox_id> <password>"
@@ -36,9 +42,10 @@ fi
 readonly ID="$1"
 readonly PASSWORD="$2"
 
-USERNAME="${DEFAULT_USERNAME_INIT}-${ID}"
-if [[ "${SANDBOX_USERNAME_INIT}" ]]; then
+if [[ -n "${SANDBOX_USERNAME_INIT}" ]]; then
   USERNAME="${SANDBOX_USERNAME_INIT}-${ID}"
+else
+  USERNAME="${DEFAULT_USERNAME_INIT}-${ID}"
 fi
 
 # Validate the existence of account
diff --git a/sandbox/del_sandbox_account b/sandbox/del_sandbox_account
--- a/sandbox/del_sandbox_account
+++ b/sandbox/del_sandbox_account
@@ -8,13 +8,6 @@ set -o pipefail
 
 DEFAULT_SANDBOX_SCRIPT_CONF="${HOME}/sandbox/scripts/sandbox_script.conf.default"
 
-# Inlcude script configuration
-if [[ "${SANDBOX_SCRIPT_CONF}" ]]; then
-  source "${SANDBOX_SCRIPT_CONF}"
-else
-  source "${DEFAULT_SANDBOX_SCRIPT_CONF}"
-fi
-
 # Output utilities
 err() {
   echo -e "$@" >&2
@@ -26,6 +19,19 @@ failed() {
   printf "\033[0m\n" >&1  # reset color for stdout
 }
 
+# Inlcude script configuration
+readonly SCRIPT_CONF="${SANDBOX_SCRIPT_CONF:-${DEFAULT_SANDBOX_SCRIPT_CONF}}"
+if [[ -n "${SCRIPT_CONF}" ]]; then
+  source "${SCRIPT_CONF}"
+  if [[ "$?" -ne 0 ]]; then
+    err "Failed to load script configuration: ${SCRIPT_CONF}"
+    exit 5
+  fi
+else
+  err "Script configuration is not specified"
+  exit 4
+fi
+
 # Validate command parameters
 if [[ "$#" -lt 1 ]]; then
   err "Usage: $(basename "$0") <sandbox_id>"
@@ -35,18 +41,28 @@ fi
 # Set variables
 readonly ID="$1"
 
-USERNAME="${DEFAULT_USERNAME_INIT}-${ID}"
-if [[ "${SANDBOX_USERNAME_INIT}" ]]; then
-  USERNAME="${SANDBOX_USERNAME_INIT}-${ID}"
+if [[ -n "${SANDBOX_USERNAME_INIT}" ]]; then
+  readonly USERNAME="${SANDBOX_USERNAME_INIT}-${ID}"
+else
+  readonly USERNAME="${DEFAULT_USERNAME_INIT}-${ID}"
 fi
 
-PEM_HOME="${DEFAULT_PEM_HOME}"
-if [[ "${SANDBOX_PEM_HOME}" ]]; then
-  PEM_HOME="${SANDBOX_PEM_HOME}"
+if [[ -n "${SANDBOX_USER_HOME_ROOT}" ]]; then
+  readonly USER_HOME_ROOT="${SANDBOX_USER_HOME_ROOT}"
+elif [[ -n "${DEFAULT_USER_HOME_ROOT}" ]]; then
+  readonly USER_HOME_ROOT="${DEFAULT_USER_HOME_ROOT}"
+else
+  readonly USER_HOME_ROOT="/home"
+fi
+
+if [[ -n "${SANDBOX_PEM_HOME}" ]]; then
+  readonly PEM_HOME="${SANDBOX_PEM_HOME}"
+else
+  readonly PEM_HOME="${DEFAULT_PEM_HOME}"
 fi
 
 # Delete account and the associated home folder and mailbox file
-sudo rm -rf "/home/${USERNAME}" && 
+sudo rm -rf "${USER_HOME_ROOT}/${USERNAME}" && 
 sudo rm -f "/var/spool/mail/${USERNAME}" && 
 sudo userdel "${USERNAME}"
 
diff --git a/sandbox/ls_sandbox_accounts b/sandbox/ls_sandbox_accounts
--- a/sandbox/ls_sandbox_accounts
+++ b/sandbox/ls_sandbox_accounts
@@ -8,17 +8,35 @@ set -o pipefail
 
 DEFAULT_SANDBOX_SCRIPT_CONF="${HOME}/sandbox/scripts/sandbox_script.conf.default"
 
+# Output utilities
+err() {
+  echo -e "$@" >&2
+}
+
+failed() {
+  printf "\033[31m" >&1  # set to red font for stdout
+  printf "$@" >&2  # output to stderr
+  printf "\033[0m\n" >&1  # reset color for stdout
+}
+
 # Inlcude script configuration
-if [[ "${SANDBOX_SCRIPT_CONF}" ]]; then
-  source "${SANDBOX_SCRIPT_CONF}"
+readonly SCRIPT_CONF="${SANDBOX_SCRIPT_CONF:-${DEFAULT_SANDBOX_SCRIPT_CONF}}"
+if [[ -n "${SCRIPT_CONF}" ]]; then
+  source "${SCRIPT_CONF}"
+  if [[ "$?" -ne 0 ]]; then
+    err "Failed to load script configuration: ${SCRIPT_CONF}"
+    exit 5
+  fi
 else
-  source "${DEFAULT_SANDBOX_SCRIPT_CONF}"
+  err "Script configuration is not specified"
+  exit 4
 fi
 
 # Set variables
-USERNAME_INIT="${DEFAULT_USERNAME_INIT}"
-if [[ "${SANDBOX_USERNAME_INIT}" ]]; then
-  USERNAME_INIT="${SANDBOX_USERNAME_INIT}"
+if [[ -n "${SANDBOX_USERNAME_INIT}" ]]; then
+  readonly USERNAME_INIT="${SANDBOX_USERNAME_INIT}"
+else
+  readonly USERNAME_INIT="${DEFAULT_USERNAME_INIT}"
 fi
 
 # List usernames according to the specified pattern
